eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    config:
      override.system-properties: false # 각 서비스의 application.yml의 설정을 무시하고 config-server의 설정을 사용하도록 설정

management:
  tracing:
    sampling:
      probability: 1.0