spring:
  data:
    mongodb:
      username: hyunwoo
      password: hyunwoo
      host: localhost #MongoDB가 위치한 서버의 호스트명
      port: 27017 #MongoDB가 사용하는 포트
      database: customer #연결할 MongoDB 데이터베이스 이름 만약 없으면, 애플리케이션이 MongoDB와 최초로 연결할 때 자동으로 생성
      authentication-database: admin #인증에 사용할 데이터베이스를 지정

server:
  port: 8090